FROM python:3.10.2-slim 

WORKDIR /app 

COPY ../pyproject.toml pyproject.toml   

RUN pip install uv && uv pip install --system -r pyproject.toml 

COPY ../ . 

# RUN export PYTHONPATH=$PYTHONPATH:/app/

CMD ["python","-m",  "model-train.train"]
